### ISSUE TITLE
Readme inconsistency

### ISSUE THREAD

**Issue by daniel-shuy** [slick/slick-codegen-example#10]
Sorry, being OCD. Just wanted to point out that `project/Build.scala` in the README.md should be updated to `build.sbt` instead.

**Comment by cvogt** [comment]
thx, fixed in https://github.com/slick/slick-codegen-example/commit/5386ee4deae0cbd3e5f825cc724b7a7b5f95589b

btw, github has an "edit file" button, which makes it super easy to PR things like this. might be easier than explaining ;).

**Comment by daniel-shuy** [comment]
Thanks. I'm aware of it, its just that some projects are pretty particular about discussing before creating a Pull Request, though I guess I should've known in this case, given the scale of this project.
