### ISSUE TITLE
Minor: Fix the SBT Compile Example Warning

### ISSUE THREAD

**Issue by imanabu** [slick/slick-codegen-example#11]
The line to in the slickCodeGen example, with  `version=0.13.15`

    slickCodeGenTask = (sourceManaged, dependencyClasspath in Compile, runner in Compile, streams) map { (dir, cp, r, s) =>

Results in a warning message under 

    warning: method t4ToTable4 in object Scoped is deprecated: The sbt 0.10 style DSL is deprecated: '(k1, k2) map { (x, y) => ... }' should now be '{ val x = k1.value; val y = k2.value }'.

**Comment by imanabu** [comment]
The Fix could be;

    lazy val slickCodeGenTask = Def task {
      val dir = sourceManaged.value
      val cp = (dependencyClasspath in Compile).value
      val r = (runner in Compile).value
      val s = streams.value
      ...
   }

**Comment by SethTisue** [comment]
if this wasn't fixed by #14, let us know
