### ISSUE TITLE
set up CI in this repo

### ISSUE THREAD

**Issue by SethTisue** [slick/slick-codegen-example#18]
would someone like to contribute a Travis-CI or GitHub Actions config...?

**Comment by SethTisue** [comment]
for some reason Circle-CI seems to be enabled, and that's where the red X at the top of this page is coming from. we have no config file, and thus:

```
#!/bin/sh -eo pipefail
# No configuration was found in your project. Please refer to https://circleci.com/docs/2.0/ to get started with your configuration.
# 
# -------
# Warning: This configuration was auto-generated to show you the message above.
# Don't rerun this job. Rerunning will have no effect.
false

Exited with code exit status 1
CircleCI received exit code 1
```

I tried to disable CircleCI and failed; at https://app.circleci.com/settings/project/github/slick/slick-codegen-example it just says "Loading..." and spins forever

I guess for now it doesn't matter, if we have no working CI, it doesn't matter if some non-working CI is present.

**Comment by SethTisue** [comment]
CircleCI is disabled now, I think, not sure why removing it worked this time when it didn't before

**Comment by SethTisue** [comment]
the whole Slick organization is now on Lightbend's paid Travis-CI plan, so if someone wants to pursue that option, it's available

**Comment by nafg** [comment]
Added sbt-github-actions (via my sbt-mergify-github-actions)

**Comment by nafg** [comment]
(and submitted a PR to add to scala steward so expect a downpour soon...)
