### ISSUE TITLE
could not parse timestamp

### ISSUE THREAD

**Issue by linsheng9731** [slick/slick-codegen-example#4]
**Could not parse default value Some(timezone('utc'::text, now()))**
jdbcDriver = "org.postgresql.Driver"
slickDriver ="slick.driver.PostgresDriver" 
java_version = '1.8.0_40'
Loading global plugins from /Users/damon/.sbt/0.13/plugins

**Comment by SethTisue** [comment]
closing for lack of details. if this still an issue please add details or open a new ticket
