### ISSUE TITLE
Won't compile in eclipse presentation compiler

### ISSUE THREAD

**Issue by matanster** [slick/slick-codegen-example#5]
After https://github.com/typesafehub/sbteclipse/pull/242 has settled down, looks like scala-ide will not be able to find/compile the generated source file (although sbt will). Of course this is more of a scala-ide issue, but I posted it here as I assume a demo project is expected to work (also) in eclipse.

**Comment by matanster** [comment]
As I have learned, scala-ide is entirely decoupled from this part of project configuration, so posted an enquiry at a very much related sbteclipse issue.

**Comment by SethTisue** [comment]
ScalaIDE is dead
