### ISSUE TITLE
improve this to filter on schema, table-type, table-name

### ISSUE THREAD

**Issue by LogicalTime** [slick/slick-codegen-example#7]
Would like to be able to provide schema, table-types-desired and table-names-desired for this generator. Perhaps this should be one one level up so we have a main class that can do this.

**Comment by cvogt** [comment]
how about a PR :)?

**Comment by LogicalTime** [comment]
Yep, I'll try and get to it when I have a day off. I have the code it's just in a messy form and uses akka streams so I'll have to get rid of that dependency.

**Comment by SethTisue** [comment]
is this still relevant, should the ticket stay open?
